---

- name: Add Docker repository key
  apt_key: url="https://get.docker.io/gpg" state=present validate_certs=no

- name: Add Docker repository
  apt_repository:
    repo: 'deb http://get.docker.io/ubuntu docker main'
    update_cache: yes

- name: Install Docker
  apt: pkg=lxc-docker
  notify: "Start Docker"

- name: Install pip
  apt: pkg=python-pip state=present

- name: Install docker-py
  pip: name=docker-py state=present
