---

- name: add nginx ppa
  apt_repository: repo='ppa:nginx/stable' state=present update_cache=yes
  tags: nginx

- name: install nginx
  apt: pkg=nginx state=latest
  tags: nginx

- name: remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: nginx
  notify:
    - Restart Nginx
